import type { RuleSet, SourceMetadata } from '@/rules/schema/ruleSet';
import {
  add,
  and,
  capability,
  config,
  configBool,
  gte,
  ifElse,
  input,
  inputBool,
  lookup,
  lte,
  mul,
  neg,
  not,
  num,
  or,
  sumTeams,
} from '@/rules/expression/builders';

export const PAGAT_SOURCE: SourceMetadata = {
  name: 'Pagat',
  title: 'Canasta: rules and variations',
  url: 'https://www.pagat.com/rummy/canasta.html',
  retrievedAt: '2026-09-19',
};

export const BICYCLE_SOURCE: SourceMetadata = {
  name: 'Bicycle',
  title: 'Canasta Rules',
  url: 'https://bicyclecards.com/how-to-play/canasta',
  retrievedAt: '2026-09-19',
};

/**
 * Classic Canasta.
 *
 * Every value here is verified against Pagat and cross-checked against Bicycle;
 * see docs/RULESET_RESEARCH.md §1 for the per-value table.
 *
 * Three values the earlier specification had wrong, now corrected to the
 * sources: the threshold bounds are 1495/2995 (not 1499/2999); going out
 * concealed is 200 *in total*, replacing the normal 100 rather than stacking on
 * it; and red threes count negative for a team that never melded.
 */
export const classic: RuleSet = {
  id: 'builtin.classic',
  name: 'Classic Canasta',
  description: 'De oorspronkelijke, wereldwijd verspreide regelset. 4 spelers in 2 teams.',
  version: 1,
  engineVersion: 1,
  origin: 'builtin',
  family: 'classic',
  locked: true,
  source: PAGAT_SOURCE,
  additionalSources: [BICYCLE_SOURCE],
  provenance: {
    entries: [
      {
        path: 'endGame.winner.tie',
        status: 'app-policy',
        note: 'Geen enkele bron beschrijft een exact gelijkspel. Deze app speelt dan een extra ronde.',
      },
      {
        path: 'threes.black.freezesPile',
        status: 'secondary-source',
        note: 'Pagat: een zwarte drie bevriest de stapel niet. Bicycle zegt van wel; instelbaar als huisregel.',
        source: PAGAT_SOURCE,
      },
    ],
  },

  configuration: {
    players: { min: 4, max: 4, default: 4 },
    teams: { mode: 'partnership', count: 2, teamSize: 2 },
    deck: { standardDecks: 2, jokers: 4, totalCards: 108 },
    dealing: { cardsPerPlayer: 11, drawCount: 1, discardCount: 1 },

    scoring: {
      cardValues: {
        joker: 50,
        ace: 20,
        two: 20,
        king: 10,
        queen: 10,
        jack: 10,
        ten: 10,
        nine: 10,
        eight: 10,
        seven: 5,
        six: 5,
        five: 5,
        four: 5,
        threeBlack: 5,
      },
      canastas: { natural: 500, mixed: 300 },
      // Concealed replaces normal: 200 in total, not 100 + 200.
      goingOut: { none: 0, normal: 100, concealed: 200 },
    },

    threes: {
      red: {
        enabled: true,
        // Index is the count; four red threes are 800, not 4 × 100.
        valueByCount: [0, 100, 200, 300, 800],
        requiresMeld: true,
        maxPerTeam: 4,
      },
      black: {
        enabled: false,
        meldValue: 5,
        freezesPile: false,
        valueByCount: [0, 0, 0, 0, 0],
      },
      swingWithCanastas: false,
    },

    initialMeld: {
      enabled: true,
      thresholds: [
        { minScore: null, maxScore: -1, required: 15 },
        { minScore: 0, maxScore: 1495, required: 50 },
        { minScore: 1500, maxScore: 2995, required: 90 },
        { minScore: 3000, maxScore: null, required: 120 },
      ],
      requiresCleanTriple: false,
      countTopDiscardCard: true,
      splashAllowed: false,
    },

    goOut: {
      minimumCanastas: 1,
      concealedEnabled: true,
      discardRequired: false,
      permissionFromPartner: true,
    },

    penalties: {
      handCardsSubtracted: true,
      incompleteMelds: [],
      minimumRoundScore: null,
    },

    talon: { enabled: false, firstTeamCards: 0, secondTeamCards: 0, minimumStockCards: 0 },

    specialHands: { enabled: false, mode: 'replace', hands: [] },

    endGame: {
      targetScore: 5000,
      evaluateAfterRound: true,
      winner: { strategy: 'highest-score', tie: 'play-extra-round' },
    },
  },

  capabilities: {
    teams: true,
    initialMeld: true,
    redThrees: true,
    blackThrees: false,
    specialHands: false,
    wildCanastas: false,
    specialCanastas: false,
    concealedGoingOut: true,
    multipleCanastaTypes: true,
    handPenalty: true,
    incompleteCanastaPenalty: false,
    talon: false,
  },

  fields: [
    {
      id: 'cardPoints',
      type: 'points',
      label: 'Kaartpunten op tafel',
      category: 'cards',
      order: 10,
      defaultValue: 0,
      min: 0,
      max: 20000,
      step: 5,
    },
    {
      id: 'naturalCanastas',
      type: 'count',
      label: "Natuurlijke Canasta's",
      category: 'canastas',
      order: 20,
      defaultValue: 0,
      min: 0,
      max: 10,
      step: 1,
    },
    {
      id: 'mixedCanastas',
      type: 'count',
      label: "Gemengde Canasta's",
      category: 'canastas',
      order: 30,
      defaultValue: 0,
      min: 0,
      max: 10,
      step: 1,
    },
    {
      id: 'redThrees',
      type: 'count',
      label: 'Rode drieën',
      category: 'threes',
      order: 40,
      defaultValue: 0,
      min: 0,
      max: 4,
      step: 1,
      visibleWhen: capability('redThrees'),
    },
    {
      id: 'opened',
      type: 'boolean',
      label: 'Team heeft geopend',
      hint: 'Zonder opening tellen rode drieën negatief.',
      category: 'threes',
      order: 45,
      defaultValue: true,
      visibleWhen: {
        op: 'and',
        args: [capability('redThrees'), configBool('threes.red.requiresMeld')],
      },
    },
    {
      id: 'wentOut',
      type: 'boolean',
      label: 'Uitgegaan',
      category: 'goingOut',
      order: 50,
      defaultValue: false,
    },
    {
      id: 'concealedGoingOut',
      type: 'boolean',
      label: 'Verborgen uitgegaan',
      hint: 'Hele hand in één beurt gemeld, inclusief een Canasta.',
      category: 'goingOut',
      order: 55,
      defaultValue: false,
      visibleWhen: {
        op: 'and',
        args: [capability('concealedGoingOut'), configBool('goOut.concealedEnabled')],
      },
    },
    {
      id: 'cardsInHand',
      type: 'points',
      label: 'Kaarten in hand',
      category: 'penalties',
      order: 60,
      defaultValue: 0,
      min: 0,
      max: 5000,
      step: 5,
      visibleWhen: configBool('penalties.handCardsSubtracted'),
    },
  ],

  scoringRules: [
    {
      id: 'cardPoints',
      label: 'Kaartpunten',
      kind: 'cards',
      order: 10,
      compute: input('cardPoints'),
    },
    {
      id: 'naturalCanastaBonus',
      label: 'Natural Canasta',
      kind: 'bonus',
      order: 20,
      compute: mul(input('naturalCanastas'), config('scoring.canastas.natural')),
      detail: {
        count: input('naturalCanastas'),
        unitValue: config('scoring.canastas.natural'),
      },
      explainTemplate: "{count} natuurlijke Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'mixedCanastaBonus',
      label: 'Mixed Canasta',
      kind: 'bonus',
      order: 30,
      compute: mul(input('mixedCanastas'), config('scoring.canastas.mixed')),
      detail: {
        count: input('mixedCanastas'),
        unitValue: config('scoring.canastas.mixed'),
      },
      explainTemplate: "{count} gemengde Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'redThreeBonus',
      label: 'Rode drieën',
      kind: 'bonus',
      order: 40,
      appliesWhen: capability('redThrees'),
      // Verified: a team that never melded scores its red threes negative.
      compute: ifElse(
        or(not(configBool('threes.red.requiresMeld')), inputBool('opened')),
        lookup('threes.red.valueByCount', input('redThrees')),
        neg(lookup('threes.red.valueByCount', input('redThrees'))),
      ),
      detail: { count: input('redThrees') },
      explainTemplate: '{count} rode drie(ën)',
    },
    {
      id: 'goingOutBonus',
      label: 'Uitgaan',
      kind: 'bonus',
      order: 50,
      appliesWhen: inputBool('wentOut'),
      // Concealed *replaces* the normal bonus (200 in total), it does not stack
      // with it. Expressing it as one nested choice keeps that impossible to get
      // wrong, and keeps the values in configuration where house rules reach them.
      compute: ifElse(
        and(configBool('goOut.concealedEnabled'), inputBool('concealedGoingOut')),
        config('scoring.goingOut.concealed'),
        config('scoring.goingOut.normal'),
      ),
      detail: {
        bonus: ifElse(
          and(configBool('goOut.concealedEnabled'), inputBool('concealedGoingOut')),
          config('scoring.goingOut.concealed'),
          config('scoring.goingOut.normal'),
        ),
      },
      explainTemplate: 'Uitgaan: +{bonus}',
    },
    {
      id: 'handPenalty',
      label: 'Kaarten in hand',
      kind: 'penalty',
      order: 90,
      appliesWhen: configBool('penalties.handCardsSubtracted'),
      compute: neg(input('cardsInHand')),
      detail: { points: input('cardsInHand') },
      explainTemplate: 'Kaarten in hand: −{points}',
    },
  ],

  settings: [
    {
      key: 'endGame.targetScore',
      label: 'Doelscore',
      type: 'number',
      category: 'game',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 10,
      min: 500,
      max: 50000,
      step: 500,
    },
    {
      key: 'dealing.cardsPerPlayer',
      label: 'Kaarten per speler',
      type: 'number',
      category: 'setup',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 20,
      min: 1,
      max: 30,
    },
    {
      key: 'dealing.drawCount',
      label: 'Kaarten trekken per beurt',
      type: 'number',
      category: 'setup',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 25,
      min: 1,
      max: 4,
    },
    {
      key: 'teams.count',
      label: 'Aantal teams',
      type: 'number',
      category: 'setup',
      editable: false,
      effect: 'advisory',
      status: 'verified',
      order: 30,
    },
    {
      key: 'deck.standardDecks',
      label: 'Aantal kaartspellen',
      type: 'number',
      category: 'setup',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 40,
      min: 1,
      max: 6,
    },
    {
      key: 'deck.jokers',
      label: 'Aantal jokers',
      type: 'number',
      category: 'setup',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 50,
      min: 0,
      max: 12,
    },
    {
      key: 'scoring.canastas.natural',
      label: 'Natuurlijke Canasta',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 60,
      min: 0,
      max: 5000,
      step: 50,
    },
    {
      key: 'scoring.canastas.mixed',
      label: 'Gemengde Canasta',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 70,
      min: 0,
      max: 5000,
      step: 50,
    },
    {
      key: 'scoring.goingOut.normal',
      label: 'Uitgaan bonus',
      type: 'number',
      category: 'goingOut',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 80,
      min: 0,
      max: 2000,
      step: 50,
    },
    {
      key: 'scoring.goingOut.concealed',
      label: 'Verborgen uitgaan bonus (totaal)',
      help: 'Vervangt de normale uitgaanbonus, telt er niet bij op.',
      type: 'number',
      category: 'goingOut',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 90,
      min: 0,
      max: 5000,
      step: 50,
      visibleWhen: configBool('goOut.concealedEnabled'),
    },
    {
      key: 'goOut.concealedEnabled',
      label: 'Verborgen uitgaan',
      type: 'boolean',
      category: 'goingOut',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 100,
    },
    {
      key: 'goOut.minimumCanastas',
      label: "Minimum aantal Canasta's om uit te gaan",
      type: 'number',
      category: 'goingOut',
      editable: true,
      effect: 'validation',
      status: 'verified',
      order: 110,
      min: 0,
      max: 6,
    },
    {
      key: 'goOut.permissionFromPartner',
      label: 'Toestemming partner vragen',
      type: 'boolean',
      category: 'goingOut',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 120,
    },
    {
      key: 'threes.red.valueByCount',
      label: 'Rode drieën',
      type: 'numberTable',
      category: 'threes',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 130,
      itemLabels: ['geen', '1 rode 3', '2 rode 3', '3 rode 3', '4 rode 3'],
    },
    {
      key: 'threes.red.requiresMeld',
      label: 'Rode drieën negatief zonder opening',
      type: 'boolean',
      category: 'threes',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 140,
    },
    {
      key: 'threes.black.freezesPile',
      label: 'Zwarte drie bevriest de aflegstapel',
      help: 'Pagat: nee. Bicycle: ja. Standaard volgt Pagat.',
      type: 'boolean',
      category: 'threes',
      editable: true,
      effect: 'advisory',
      status: 'secondary-source',
      statusNote: 'Bronnen spreken elkaar tegen; Pagat is leidend voor Classic.',
      order: 150,
    },
    {
      key: 'initialMeld.thresholds',
      label: 'Openingsmeldingsgrenzen',
      type: 'thresholds',
      category: 'initialMeld',
      editable: true,
      effect: 'validation',
      status: 'verified',
      order: 160,
    },
    {
      key: 'initialMeld.countTopDiscardCard',
      label: 'Bovenste aflegkaart telt mee voor de opening',
      type: 'boolean',
      category: 'initialMeld',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 170,
    },
    {
      key: 'penalties.handCardsSubtracted',
      label: 'Kaarten in hand aftrekken',
      type: 'boolean',
      category: 'penalties',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 180,
    },
    {
      key: 'endGame.winner.tie',
      label: 'Bij exact gelijkspel',
      help: 'Geen van de geraadpleegde bronnen beschrijft deze situatie. Dit is een keuze van de app.',
      type: 'select',
      category: 'game',
      editable: true,
      effect: 'computed',
      status: 'app-policy',
      statusNote: 'App-keuze, geen bronregel.',
      order: 190,
      options: [
        { value: 'play-extra-round', label: 'Extra ronde spelen' },
        { value: 'shared-win', label: 'Gedeelde winst' },
      ],
    },
  ],

  constraints: [
    {
      id: 'targetScorePositive',
      kind: 'expr',
      severity: 'error',
      message: 'Doelscore moet groter zijn dan 0.',
      paths: ['endGame.targetScore'],
      assert: { op: 'cmp', cmp: 'gt', left: config('endGame.targetScore'), right: num(0) },
    },
    {
      id: 'cardsPerPlayerPositive',
      kind: 'expr',
      severity: 'error',
      message: 'Kaarten per speler moet groter zijn dan 0.',
      paths: ['dealing.cardsPerPlayer'],
      assert: { op: 'cmp', cmp: 'gt', left: config('dealing.cardsPerPlayer'), right: num(0) },
    },
    {
      id: 'naturalCanastaNotNegative',
      kind: 'expr',
      severity: 'error',
      message: 'Canasta-bonus mag niet negatief zijn.',
      paths: ['scoring.canastas.natural'],
      assert: gte(config('scoring.canastas.natural'), num(0)),
    },
    {
      id: 'mixedCanastaNotNegative',
      kind: 'expr',
      severity: 'error',
      message: 'Canasta-bonus mag niet negatief zijn.',
      paths: ['scoring.canastas.mixed'],
      assert: gte(config('scoring.canastas.mixed'), num(0)),
    },
    {
      id: 'naturalAtLeastMixed',
      kind: 'expr',
      severity: 'warning',
      message: 'Ongebruikelijk: een gemengde Canasta levert meer op dan een natuurlijke.',
      paths: ['scoring.canastas.natural', 'scoring.canastas.mixed'],
      assert: gte(config('scoring.canastas.natural'), config('scoring.canastas.mixed')),
    },
    {
      id: 'concealedNeedsBonus',
      kind: 'expr',
      severity: 'error',
      message: 'Verborgen uitgaan staat aan maar er is geen bonus gedefinieerd.',
      paths: ['goOut.concealedEnabled', 'scoring.goingOut.concealed'],
      assert: or(
        not(configBool('goOut.concealedEnabled')),
        gte(config('scoring.goingOut.concealed'), num(0)),
      ),
    },
    {
      id: 'minimumCanastasSane',
      kind: 'expr',
      severity: 'error',
      message: "Minimum aantal Canasta's om uit te gaan ligt buiten het haalbare bereik.",
      paths: ['goOut.minimumCanastas'],
      assert: {
        op: 'and',
        args: [
          gte(config('goOut.minimumCanastas'), num(0)),
          lte(config('goOut.minimumCanastas'), num(6)),
        ],
      },
    },
    {
      id: 'thresholdsContiguous',
      kind: 'module',
      severity: 'error',
      module: 'core.thresholdsContiguous',
      paths: ['initialMeld.thresholds'],
    },
  ],

  roundRules: [
    {
      id: 'atMostOneGoOut',
      kind: 'module',
      scope: 'round',
      severity: 'error',
      module: 'core.atMostOneGoOut',
    },
    {
      id: 'redThreesTotal',
      kind: 'expr',
      scope: 'round',
      severity: 'warning',
      message: 'Er zijn meer rode drieën ingevoerd dan er in het spel zitten.',
      fieldId: 'redThrees',
      assert: lte(sumTeams('redThrees'), mul(num(2), config('deck.standardDecks'))),
    },
    {
      id: 'goOutNeedsCanasta',
      kind: 'expr',
      scope: 'team',
      severity: 'warning',
      message: "Uitgaan vereist minimaal {min} Canasta('s).",
      fieldId: 'wentOut',
      messageValues: { min: 'goOut.minimumCanastas' },
      appliesWhen: inputBool('wentOut'),
      assert: gte(
        add(input('naturalCanastas'), input('mixedCanastas')),
        config('goOut.minimumCanastas'),
      ),
    },
    {
      id: 'goingOutTeamHasNoHandCards',
      kind: 'expr',
      scope: 'team',
      severity: 'warning',
      message: 'Het team dat uitgaat heeft normaal geen kaarten meer in de hand.',
      fieldId: 'cardsInHand',
      appliesWhen: inputBool('wentOut'),
      assert: { op: 'cmp', cmp: 'eq', left: input('cardsInHand'), right: num(0) },
    },
    {
      id: 'concealedRequiresGoingOut',
      kind: 'expr',
      scope: 'team',
      severity: 'error',
      message: 'Verborgen uitgaan kan alleen als het team ook is uitgegaan.',
      fieldId: 'concealedGoingOut',
      appliesWhen: inputBool('concealedGoingOut'),
      assert: inputBool('wentOut'),
    },
  ],
};
