import type { NumExpr } from '@/rules/schema/expression';
import type { RuleSet, SourceMetadata } from '@/rules/schema/ruleSet';
import {
  add,
  capability,
  config,
  configBool,
  count,
  eq,
  gt,
  gte,
  ifElse,
  input,
  inputBool,
  lookup,
  lte,
  mul,
  neg,
  not,
  num,
  or,
  str,
  sumOver,
} from '@/rules/expression/builders';
import { PAGAT_SOURCE } from './classic';

export const CLA_SOURCE: SourceMetadata = {
  name: 'Canasta League of America',
  title: 'Modern American Canasta: How to Play, Meld, and Score',
  url: 'https://canastaleague.org/rules/',
  retrievedAt: '2026-09-19',
};

/**
 * Total completed canastas, across every category this variant recognises.
 *
 * This drives the swing table: threes and melded card values are subtracted
 * with no canasta, ignored with one, and added with two or more.
 */
const totalCanastas: NumExpr = add(
  input('naturalCanastas'),
  input('mixedCanastas'),
  input('wildCanastas'),
  input('jokerCanastas'),
  input('twosCanastas'),
  input('acesCanastas'),
  input('sevensCanastas'),
);

/** True when this team laid down a special hand. */
const hasSpecialHand = gt(count('specialHands'), num(0));

/**
 * Applies the swing sign to a value: negative with no canasta, nothing with
 * one, positive with two or more.
 */
const swing = (value: NumExpr): NumExpr =>
  ifElse(gte(totalCanastas, num(2)), value, ifElse(eq(totalCanastas, num(0)), neg(value), num(0)));

/**
 * Modern American Canasta.
 *
 * Primary source: Canasta League of America, which leads on conflicting rules.
 * Pagat supplies setup details the CLA does not state — player count, team
 * count and deck composition — recorded below as `secondary-source`.
 *
 * See docs/RULESET_RESEARCH.md §2 for the per-value table and the four
 * documented conflicts with Pagat.
 */
export const modernAmerican: RuleSet = {
  id: 'builtin.modernAmerican',
  name: 'Modern American Canasta',
  description:
    "Striktere variant met 13 kaarten, speciale handen en Canasta's die met je drieën meebewegen.",
  version: 1,
  engineVersion: 1,
  origin: 'builtin',
  family: 'modernAmerican',
  locked: true,
  source: CLA_SOURCE,
  additionalSources: [PAGAT_SOURCE],
  provenance: {
    entries: [
      {
        path: 'players.default',
        status: 'secondary-source',
        note: 'De CLA noemt het spelersaantal niet expliciet; aangevuld uit Pagat (4 spelers in vaste partnerships).',
        source: PAGAT_SOURCE,
      },
      {
        path: 'teams.count',
        status: 'secondary-source',
        note: 'De CLA noemt het teamaantal niet expliciet; aangevuld uit Pagat (2 teams van 2).',
        source: PAGAT_SOURCE,
      },
      {
        path: 'deck.standardDecks',
        status: 'secondary-source',
        note: 'De CLA noemt het deckaantal niet; aangevuld uit Pagat (2 standaard decks).',
        source: PAGAT_SOURCE,
      },
      {
        path: 'deck.totalCards',
        status: 'secondary-source',
        note: 'Volgt uit 2 decks + 4 jokers; de CLA noemt het totaal niet.',
        source: PAGAT_SOURCE,
      },
      {
        path: 'goOut.concealedEnabled',
        status: 'not-specified',
        note: 'De Canasta League of America beschrijft verborgen uitgaan niet voor Modern American. Deze regelset heeft het daarom uit staan; via huisregels is het in te schakelen. Dit is géén expliciet verbod.',
      },
      {
        path: 'initialMeld.splashAllowed',
        status: 'not-specified',
        note: 'Pagat beschrijft "The Splash"; de CLA noemt het niet. Standaard uit, in te schakelen als huisregel.',
      },
      {
        path: 'endGame.winner.tie',
        status: 'app-policy',
        note: 'Geen enkele bron beschrijft een exact gelijkspel. Deze app speelt dan een extra ronde.',
      },
    ],
    notes:
      'Conflicten met Pagat (Garbage 2.000, onvolledige wildmeld met vier jokers −2.500, wildcard-meld als opening) zijn ten gunste van de CLA beslist; zie docs/RULESET_RESEARCH.md §2.14.',
  },

  configuration: {
    players: { min: 4, max: 4, default: 4 },
    teams: { mode: 'partnership', count: 2, teamSize: 2 },
    deck: { standardDecks: 2, jokers: 4, totalCards: 108 },
    dealing: { cardsPerPlayer: 13, drawCount: 1, discardCount: 1 },

    scoring: {
      cardValues: {
        joker: 50,
        ace: 20,
        two: 20,
        king: 10,
        queen: 10,
        jack: 10,
        ten: 10,
        nine: 10,
        eight: 10,
        seven: 5,
        six: 5,
        five: 5,
        four: 5,
      },
      canastas: {
        mixed: 300,
        natural: 500,
        aces: 2500,
        sevens: 2500,
        wild: 2000,
        joker: 2500,
        twos: 3000,
      },
      // No concealed going out in this variant; see provenance.
      goingOut: { none: 0, normal: 100, concealed: 100 },
    },

    threes: {
      red: {
        enabled: true,
        valueByCount: [0, 100, 300, 500, 1000],
        // The sign comes from the canasta count, not from having melded.
        requiresMeld: false,
        maxPerTeam: 4,
      },
      black: {
        enabled: true,
        meldValue: 0,
        freezesPile: false,
        valueByCount: [0, 100, 300, 500, 1000],
      },
      swingWithCanastas: true,
    },

    initialMeld: {
      enabled: true,
      thresholds: [
        // Pagat covers what the CLA leaves open: a negative score is still 125.
        { minScore: null, maxScore: 2995, required: 125 },
        { minScore: 3000, maxScore: 4995, required: 155 },
        { minScore: 5000, maxScore: null, required: 180 },
      ],
      requiresCleanTriple: true,
      countTopDiscardCard: false,
      splashAllowed: false,
    },

    goOut: {
      minimumCanastas: 2,
      concealedEnabled: false,
      discardRequired: true,
      permissionFromPartner: true,
    },

    penalties: {
      handCardsSubtracted: true,
      incompleteMelds: [
        { id: 'aces', label: 'Onvolledige natuurlijke azenmeld', penalty: 2500 },
        { id: 'sevens', label: "Onvolledige 7'en-meld", penalty: 2500 },
        { id: 'wild', label: 'Onvolledige wildcard-meld', penalty: 2000 },
      ],
      minimumRoundScore: null,
    },

    talon: { enabled: true, firstTeamCards: 4, secondTeamCards: 3, minimumStockCards: 9 },

    specialHands: {
      enabled: true,
      // Verified in both sources: a special hand replaces the team's whole score.
      mode: 'replace',
      hands: [
        {
          id: 'pairs',
          label: 'Pairs',
          bonus: 2500,
          requirement: 'Zeven verschillende paren, geen wildcards.',
        },
        {
          id: 'wildPairs',
          label: 'Wild Pairs',
          bonus: 2000,
          requirement: "Zeven paren inclusief azen, 7'en en één passend wildpaar (2'en of jokers).",
        },
        {
          id: 'miamiPairs',
          label: 'Miami Pairs',
          bonus: 2500,
          requirement: "Zeven paren inclusief azen, 7'en en beide wildparen (JoJo en 22).",
        },
        {
          id: 'zipCode',
          label: 'Zip Code',
          bonus: 2500,
          requirement: 'Twee paren + twee drietallen + één viertal. Passende wilds toegestaan.',
        },
        {
          id: 'straight',
          label: 'Straight',
          bonus: 3000,
          requirement: 'Eén kaart van elke rang, inclusief een 3 en beide wilds.',
        },
        {
          id: 'garbage',
          label: 'Garbage',
          bonus: 3000,
          requirement: 'Twee viertallen + twee drietallen, geen wilds.',
        },
        {
          id: 'blastOff',
          label: 'Blast Off',
          bonus: 3000,
          requirement:
            'Eén vijftal + één viertal + één drietal + één paar. Passende wilds toegestaan.',
        },
        {
          id: 'triples',
          label: 'Triples',
          bonus: 3500,
          requirement: 'Vier drietallen + een passend wildpaar.',
        },
        {
          id: 'quads',
          label: 'Quads',
          bonus: 3500,
          requirement: 'Drie viertallen + een passend wildpaar.',
        },
        {
          id: 'dreamHandPlus4',
          label: 'Dream Hand Plus 4',
          bonus: 8500,
          requirement: 'Twee vijftallen + vier passende wilds. Wint het spel direct.',
        },
        {
          id: 'dreamHandPlus5',
          label: 'Dream Hand Plus 5',
          bonus: 8500,
          requirement: 'Eén vijftal + één viertal + vijf wilds. Wint het spel direct.',
        },
      ],
    },

    endGame: {
      targetScore: 8500,
      evaluateAfterRound: true,
      winner: { strategy: 'highest-score', tie: 'play-extra-round' },
    },
  },

  capabilities: {
    teams: true,
    initialMeld: true,
    redThrees: true,
    blackThrees: true,
    specialHands: true,
    wildCanastas: true,
    specialCanastas: true,
    concealedGoingOut: false,
    multipleCanastaTypes: true,
    handPenalty: true,
    incompleteCanastaPenalty: true,
    talon: true,
  },

  fields: [
    {
      id: 'cardPoints',
      type: 'points',
      label: 'Kaartpunten op tafel',
      hint: 'Zonder Canasta worden deze punten afgetrokken in plaats van opgeteld.',
      category: 'cards',
      order: 10,
      defaultValue: 0,
      min: 0,
      max: 20000,
      step: 5,
    },
    {
      id: 'specialHands',
      type: 'multiselect',
      label: 'Speciale hand',
      hint: 'Vervangt de volledige rondescore van dit team.',
      category: 'special',
      order: 15,
      defaultValue: [],
      optionsFrom: 'specialHands.hands',
      optionsLabelKey: 'label',
      visibleWhen: capability('specialHands'),
    },
    {
      id: 'naturalCanastas',
      type: 'count',
      label: "Natuurlijke Canasta's",
      category: 'canastas',
      order: 20,
      defaultValue: 0,
      min: 0,
      max: 10,
      step: 1,
    },
    {
      id: 'mixedCanastas',
      type: 'count',
      label: "Gemengde Canasta's",
      category: 'canastas',
      order: 30,
      defaultValue: 0,
      min: 0,
      max: 10,
      step: 1,
    },
    {
      id: 'acesCanastas',
      type: 'count',
      label: "Azen-Canasta's",
      hint: 'Natuurlijk, 2.500 per stuk.',
      category: 'canastas',
      order: 34,
      defaultValue: 0,
      min: 0,
      max: 2,
      step: 1,
      visibleWhen: capability('specialCanastas'),
    },
    {
      id: 'sevensCanastas',
      type: 'count',
      label: "Zevens-Canasta's",
      hint: 'Natuurlijk, 2.500 per stuk.',
      category: 'canastas',
      order: 36,
      defaultValue: 0,
      min: 0,
      max: 2,
      step: 1,
      visibleWhen: capability('specialCanastas'),
    },
    {
      id: 'wildCanastas',
      type: 'count',
      label: "Wild-Canasta's (1–3 jokers)",
      category: 'canastas',
      order: 38,
      defaultValue: 0,
      min: 0,
      max: 4,
      step: 1,
      visibleWhen: capability('wildCanastas'),
    },
    {
      id: 'jokerCanastas',
      type: 'count',
      label: "Joker-Canasta's",
      hint: "Alle vier jokers plus drie 2'en.",
      category: 'canastas',
      order: 39,
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 1,
      visibleWhen: capability('wildCanastas'),
    },
    {
      id: 'twosCanastas',
      type: 'count',
      label: "Canasta's van uitsluitend 2'en",
      category: 'canastas',
      order: 40,
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 1,
      visibleWhen: capability('wildCanastas'),
    },
    {
      id: 'redThrees',
      type: 'count',
      label: 'Rode drieën',
      category: 'threes',
      order: 50,
      defaultValue: 0,
      min: 0,
      max: 4,
      step: 1,
      visibleWhen: capability('redThrees'),
    },
    {
      id: 'blackThrees',
      type: 'count',
      label: 'Zwarte drieën',
      category: 'threes',
      order: 55,
      defaultValue: 0,
      min: 0,
      max: 4,
      step: 1,
      visibleWhen: capability('blackThrees'),
    },
    {
      id: 'wentOut',
      type: 'boolean',
      label: 'Uitgegaan',
      category: 'goingOut',
      order: 60,
      defaultValue: false,
    },
    {
      id: 'incompleteMelds',
      type: 'multiselect',
      label: 'Onvolledige speciale melds',
      category: 'penalties',
      order: 70,
      defaultValue: [],
      optionsFrom: 'penalties.incompleteMelds',
      optionsLabelKey: 'label',
      visibleWhen: capability('incompleteCanastaPenalty'),
    },
    {
      id: 'acesInHand',
      type: 'count',
      label: 'Azen in hand',
      hint: 'Drie of meer kost 1.500 strafpunten.',
      category: 'penalties',
      order: 74,
      defaultValue: 0,
      min: 0,
      max: 8,
      step: 1,
    },
    {
      id: 'sevensInHand',
      type: 'count',
      label: "7'en in hand",
      hint: 'Drie of meer kost 1.500 strafpunten.',
      category: 'penalties',
      order: 76,
      defaultValue: 0,
      min: 0,
      max: 8,
      step: 1,
    },
    {
      id: 'cardsInHand',
      type: 'points',
      label: 'Kaarten in hand',
      category: 'penalties',
      order: 80,
      defaultValue: 0,
      min: 0,
      max: 5000,
      step: 5,
      visibleWhen: configBool('penalties.handCardsSubtracted'),
    },
  ],

  // Verified in both sources: the team that lays down a special hand scores only
  // that hand, while the opposing team scores normally. Stated once here, so
  // switching to additive special hands is a data change rather than a code one.
  exclusiveScoringModes: [
    {
      id: 'specialHandReplacesScore',
      when: {
        op: 'and',
        args: [
          configBool('specialHands.enabled'),
          {
            op: 'eqKey',
            left: { op: 'configKey', path: 'specialHands.mode' },
            right: str('replace'),
          },
          hasSpecialHand,
        ],
      },
      only: ['specialHandBonus'],
    },
  ],

  scoringRules: [
    {
      id: 'specialHandBonus',
      label: 'Speciale hand',
      kind: 'bonus',
      order: 5,
      appliesWhen: hasSpecialHand,
      compute: sumOver('specialHands', 'specialHands.hands', 'bonus'),
      detail: { handCount: count('specialHands') },
      explainTemplate: 'Uitgegaan met {handCount} speciale hand(en)',
    },
    {
      id: 'cardPoints',
      label: 'Kaartpunten',
      kind: 'cards',
      order: 10,
      // With no canasta the melded card values are subtracted instead of added.
      compute: ifElse(gte(totalCanastas, num(1)), input('cardPoints'), neg(input('cardPoints'))),
      detail: { points: input('cardPoints'), canastas: totalCanastas },
      explainTemplate: 'Gemelde kaarten: {points} punten bij {canastas} Canasta(’s)',
    },
    {
      id: 'naturalCanastaBonus',
      label: 'Natural Canasta',
      kind: 'bonus',
      order: 20,
      compute: mul(input('naturalCanastas'), config('scoring.canastas.natural')),
      detail: { count: input('naturalCanastas'), unitValue: config('scoring.canastas.natural') },
      explainTemplate: "{count} natuurlijke Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'mixedCanastaBonus',
      label: 'Mixed Canasta',
      kind: 'bonus',
      order: 30,
      compute: mul(input('mixedCanastas'), config('scoring.canastas.mixed')),
      detail: { count: input('mixedCanastas'), unitValue: config('scoring.canastas.mixed') },
      explainTemplate: "{count} gemengde Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'acesCanastaBonus',
      label: 'Azen-Canasta',
      kind: 'bonus',
      order: 34,
      compute: mul(input('acesCanastas'), config('scoring.canastas.aces')),
      detail: { count: input('acesCanastas'), unitValue: config('scoring.canastas.aces') },
      explainTemplate: "{count} azen-Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'sevensCanastaBonus',
      label: 'Zevens-Canasta',
      kind: 'bonus',
      order: 36,
      compute: mul(input('sevensCanastas'), config('scoring.canastas.sevens')),
      detail: { count: input('sevensCanastas'), unitValue: config('scoring.canastas.sevens') },
      explainTemplate: "{count} zevens-Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'wildCanastaBonus',
      label: 'Wild-Canasta',
      kind: 'bonus',
      order: 38,
      compute: mul(input('wildCanastas'), config('scoring.canastas.wild')),
      detail: { count: input('wildCanastas'), unitValue: config('scoring.canastas.wild') },
      explainTemplate: "{count} wild-Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'jokerCanastaBonus',
      label: 'Joker-Canasta',
      kind: 'bonus',
      order: 39,
      compute: mul(input('jokerCanastas'), config('scoring.canastas.joker')),
      detail: { count: input('jokerCanastas'), unitValue: config('scoring.canastas.joker') },
      explainTemplate: "{count} joker-Canasta('s)\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'twosCanastaBonus',
      label: "Canasta van 2'en",
      kind: 'bonus',
      order: 40,
      compute: mul(input('twosCanastas'), config('scoring.canastas.twos')),
      detail: { count: input('twosCanastas'), unitValue: config('scoring.canastas.twos') },
      explainTemplate: "{count} Canasta('s) van 2'en\nBonus: +{unitValue} per stuk",
    },
    {
      id: 'threesSwing',
      label: 'Drieën',
      kind: 'bonus',
      order: 45,
      // Negative with no canasta, nothing with one, positive with two or more.
      compute: swing(
        add(
          lookup('threes.red.valueByCount', input('redThrees')),
          lookup('threes.black.valueByCount', input('blackThrees')),
        ),
      ),
      detail: {
        redThrees: input('redThrees'),
        blackThrees: input('blackThrees'),
        canastas: totalCanastas,
      },
      explainTemplate:
        '{redThrees} rode en {blackThrees} zwarte drie(ën) bij {canastas} Canasta(’s)',
    },
    {
      id: 'goingOutBonus',
      label: 'Uitgaan',
      kind: 'bonus',
      order: 50,
      appliesWhen: inputBool('wentOut'),
      compute: config('scoring.goingOut.normal'),
      detail: { bonus: config('scoring.goingOut.normal') },
      explainTemplate: 'Uitgaan: +{bonus}',
    },
    {
      id: 'incompleteMeldPenalty',
      label: 'Onvolledige speciale meld',
      kind: 'penalty',
      order: 70,
      compute: neg(sumOver('incompleteMelds', 'penalties.incompleteMelds', 'penalty')),
      detail: { melds: count('incompleteMelds') },
      explainTemplate: '{melds} onvolledige speciale meld(s)',
    },
    {
      id: 'acesInHandPenalty',
      label: 'Azen in hand',
      kind: 'penalty',
      order: 74,
      appliesWhen: gte(input('acesInHand'), num(3)),
      compute: num(-1500),
      detail: { aces: input('acesInHand') },
      explainTemplate: '{aces} azen in hand: −1.500',
    },
    {
      id: 'sevensInHandPenalty',
      label: "7'en in hand",
      kind: 'penalty',
      order: 76,
      appliesWhen: gte(input('sevensInHand'), num(3)),
      compute: num(-1500),
      detail: { sevens: input('sevensInHand') },
      explainTemplate: "{sevens} 7'en in hand: −1.500",
    },
    {
      id: 'handPenalty',
      label: 'Kaarten in hand',
      kind: 'penalty',
      order: 90,
      appliesWhen: configBool('penalties.handCardsSubtracted'),
      compute: neg(input('cardsInHand')),
      detail: { points: input('cardsInHand') },
      explainTemplate: 'Kaarten in hand: −{points}',
    },
  ],

  settings: [
    {
      key: 'endGame.targetScore',
      label: 'Doelscore',
      type: 'number',
      category: 'game',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 10,
      min: 500,
      max: 50000,
      step: 500,
    },
    {
      key: 'dealing.cardsPerPlayer',
      label: 'Kaarten per speler',
      type: 'number',
      category: 'setup',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 20,
      min: 1,
      max: 30,
    },
    {
      key: 'players.default',
      label: 'Aantal spelers',
      type: 'number',
      category: 'setup',
      editable: false,
      effect: 'advisory',
      status: 'secondary-source',
      statusNote: 'De CLA noemt dit niet; aangevuld uit Pagat.',
      order: 25,
    },
    {
      key: 'teams.count',
      label: 'Aantal teams',
      type: 'number',
      category: 'setup',
      editable: false,
      effect: 'advisory',
      status: 'secondary-source',
      statusNote: 'De CLA noemt dit niet; aangevuld uit Pagat.',
      order: 26,
    },
    {
      key: 'deck.standardDecks',
      label: 'Aantal kaartspellen',
      type: 'number',
      category: 'setup',
      editable: true,
      effect: 'advisory',
      status: 'secondary-source',
      statusNote: 'De CLA noemt dit niet; aangevuld uit Pagat.',
      order: 30,
      min: 1,
      max: 6,
    },
    {
      key: 'deck.totalCards',
      label: 'Totaal aantal kaarten',
      type: 'number',
      category: 'setup',
      editable: false,
      effect: 'advisory',
      status: 'secondary-source',
      statusNote: 'Volgt uit 2 decks + 4 jokers; de CLA noemt het totaal niet.',
      order: 32,
    },
    {
      key: 'scoring.canastas.natural',
      label: 'Natuurlijke Canasta',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 40,
      min: 0,
      max: 10000,
      step: 50,
    },
    {
      key: 'scoring.canastas.mixed',
      label: 'Gemengde Canasta',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 50,
      min: 0,
      max: 10000,
      step: 50,
    },
    {
      key: 'scoring.canastas.aces',
      label: 'Azen-Canasta',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 60,
      min: 0,
      max: 10000,
      step: 100,
    },
    {
      key: 'scoring.canastas.sevens',
      label: 'Zevens-Canasta',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 70,
      min: 0,
      max: 10000,
      step: 100,
    },
    {
      key: 'scoring.canastas.wild',
      label: 'Wild-Canasta (1–3 jokers)',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 80,
      min: 0,
      max: 10000,
      step: 100,
    },
    {
      key: 'scoring.canastas.joker',
      label: 'Joker-Canasta',
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 90,
      min: 0,
      max: 10000,
      step: 100,
    },
    {
      key: 'scoring.canastas.twos',
      label: "Canasta van 2'en",
      type: 'number',
      category: 'canastas',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 100,
      min: 0,
      max: 10000,
      step: 100,
    },
    {
      key: 'scoring.goingOut.normal',
      label: 'Uitgaan bonus',
      type: 'number',
      category: 'goingOut',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 110,
      min: 0,
      max: 2000,
      step: 50,
    },
    {
      key: 'goOut.minimumCanastas',
      label: "Minimum aantal Canasta's om uit te gaan",
      type: 'number',
      category: 'goingOut',
      editable: true,
      effect: 'validation',
      status: 'verified',
      order: 120,
      min: 0,
      max: 6,
    },
    {
      key: 'goOut.concealedEnabled',
      label: 'Verborgen uitgaan',
      help: 'De Canasta League of America beschrijft verborgen uitgaan niet voor Modern American. Deze regelset heeft het daarom uit staan; via huisregels is het in te schakelen.',
      type: 'boolean',
      category: 'goingOut',
      editable: true,
      effect: 'computed',
      status: 'not-specified',
      statusNote: 'Niet beschreven door de primaire bron. Geen expliciet verbod.',
      order: 130,
    },
    {
      key: 'threes.red.valueByCount',
      label: 'Rode drieën',
      type: 'numberTable',
      category: 'threes',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 140,
      itemLabels: ['geen', '1', '2', '3', '4'],
    },
    {
      key: 'threes.black.valueByCount',
      label: 'Zwarte drieën',
      type: 'numberTable',
      category: 'threes',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 150,
      itemLabels: ['geen', '1', '2', '3', '4'],
    },
    {
      key: 'threes.swingWithCanastas',
      label: "Drieën bewegen mee met het aantal Canasta's",
      help: 'Zonder Canasta straf, met één neutraal, met twee of meer bonus.',
      type: 'boolean',
      category: 'threes',
      editable: false,
      effect: 'computed',
      status: 'verified',
      order: 160,
    },
    {
      key: 'initialMeld.thresholds',
      label: 'Openingsmeldingsgrenzen',
      type: 'thresholds',
      category: 'initialMeld',
      editable: true,
      effect: 'validation',
      status: 'verified',
      order: 170,
    },
    {
      key: 'initialMeld.requiresCleanTriple',
      label: 'Clean Triple vereist bij opening',
      type: 'boolean',
      category: 'initialMeld',
      editable: true,
      effect: 'validation',
      status: 'verified',
      order: 180,
    },
    {
      key: 'initialMeld.splashAllowed',
      label: 'The Splash toestaan',
      help: 'Pagat beschrijft dit; de Canasta League of America noemt het niet. Standaard uit.',
      type: 'boolean',
      category: 'initialMeld',
      editable: true,
      effect: 'validation',
      status: 'not-specified',
      statusNote: 'Alleen door de secundaire bron beschreven.',
      order: 190,
    },
    {
      key: 'talon.firstTeamCards',
      label: 'Talon: eerste team',
      type: 'number',
      category: 'advanced',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 200,
      min: 0,
      max: 8,
    },
    {
      key: 'talon.secondTeamCards',
      label: 'Talon: tweede team',
      type: 'number',
      category: 'advanced',
      editable: true,
      effect: 'advisory',
      status: 'verified',
      order: 210,
      min: 0,
      max: 8,
    },
    {
      key: 'specialHands.mode',
      label: 'Speciale handen',
      type: 'select',
      category: 'specialHands',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 220,
      options: [
        { value: 'replace', label: 'Vervangen de rondescore' },
        { value: 'add', label: 'Komen bij de rondescore' },
      ],
    },
    {
      key: 'penalties.handCardsSubtracted',
      label: 'Kaarten in hand aftrekken',
      type: 'boolean',
      category: 'penalties',
      editable: true,
      effect: 'computed',
      status: 'verified',
      order: 230,
    },
    {
      key: 'endGame.winner.tie',
      label: 'Bij exact gelijkspel',
      help: 'Geen van de geraadpleegde bronnen beschrijft deze situatie. Dit is een keuze van de app.',
      type: 'select',
      category: 'game',
      editable: true,
      effect: 'computed',
      status: 'app-policy',
      statusNote: 'App-keuze, geen bronregel.',
      order: 240,
      options: [
        { value: 'play-extra-round', label: 'Extra ronde spelen' },
        { value: 'shared-win', label: 'Gedeelde winst' },
      ],
    },
  ],

  constraints: [
    {
      id: 'targetScorePositive',
      kind: 'expr',
      severity: 'error',
      message: 'Doelscore moet groter zijn dan 0.',
      paths: ['endGame.targetScore'],
      assert: gt(config('endGame.targetScore'), num(0)),
    },
    {
      id: 'cardsPerPlayerPositive',
      kind: 'expr',
      severity: 'error',
      message: 'Kaarten per speler moet groter zijn dan 0.',
      paths: ['dealing.cardsPerPlayer'],
      assert: gt(config('dealing.cardsPerPlayer'), num(0)),
    },
    {
      id: 'specialCanastasNotBelowNatural',
      kind: 'expr',
      severity: 'warning',
      message: 'Ongebruikelijk: een azen-Canasta levert minder op dan een gewone natuurlijke.',
      paths: ['scoring.canastas.aces', 'scoring.canastas.natural'],
      assert: gte(config('scoring.canastas.aces'), config('scoring.canastas.natural')),
    },
    {
      id: 'minimumCanastasSane',
      kind: 'expr',
      severity: 'error',
      message: "Minimum aantal Canasta's om uit te gaan ligt buiten het haalbare bereik.",
      paths: ['goOut.minimumCanastas'],
      assert: {
        op: 'and',
        args: [
          gte(config('goOut.minimumCanastas'), num(0)),
          lte(config('goOut.minimumCanastas'), num(6)),
        ],
      },
    },
    {
      id: 'talonNeedsStock',
      kind: 'expr',
      severity: 'error',
      message: 'De talon is ingeschakeld maar er is geen minimum stokgrootte ingesteld.',
      paths: ['talon.enabled', 'talon.minimumStockCards'],
      assert: or(not(configBool('talon.enabled')), gt(config('talon.minimumStockCards'), num(0))),
    },
    {
      id: 'thresholdsContiguous',
      kind: 'module',
      severity: 'error',
      module: 'core.thresholdsContiguous',
      paths: ['initialMeld.thresholds'],
    },
  ],

  roundRules: [
    {
      id: 'atMostOneGoOut',
      kind: 'module',
      scope: 'round',
      severity: 'error',
      module: 'core.atMostOneGoOut',
    },
    {
      id: 'goOutNeedsTwoCanastas',
      kind: 'expr',
      scope: 'team',
      severity: 'error',
      message: "Uitgaan vereist minimaal {min} Canasta's.",
      fieldId: 'wentOut',
      messageValues: { min: 'goOut.minimumCanastas' },
      appliesWhen: inputBool('wentOut'),
      assert: gte(totalCanastas, config('goOut.minimumCanastas')),
    },
    {
      id: 'specialHandExcludesOtherScoring',
      kind: 'expr',
      scope: 'team',
      severity: 'warning',
      message:
        'Een speciale hand vervangt de volledige rondescore; de overige ingevoerde waarden tellen niet mee.',
      fieldId: 'specialHands',
      appliesWhen: hasSpecialHand,
      assert: eq(add(totalCanastas, input('cardPoints')), num(0)),
    },
    {
      id: 'singleSpecialHand',
      kind: 'expr',
      scope: 'team',
      severity: 'error',
      message: 'Een team kan maar één speciale hand per ronde leggen.',
      fieldId: 'specialHands',
      appliesWhen: hasSpecialHand,
      assert: lte(count('specialHands'), num(1)),
    },
    {
      id: 'threesTotal',
      kind: 'expr',
      scope: 'round',
      severity: 'warning',
      message: 'Er zijn meer rode drieën ingevoerd dan er in het spel zitten.',
      fieldId: 'redThrees',
      assert: lte(
        { op: 'sumTeams', field: 'redThrees' },
        mul(num(2), config('deck.standardDecks')),
      ),
    },
  ],
};
